projectName: URLR
packageName: urlr
packageVersion: 3.2.2
infoName: URLR
infoEmail: contact@urlr.me
gitHost: github.com
gitUserId: URLR
gitRepoId: api-clients-generation
templateDir: openapi-generator/templates/python
