projectName: URLR
packageName: urlr
packageVersion: 2.10.3
infoName: URLR
infoEmail: contact@urlr.me
gitHost: github.com
gitUserId: urlr
gitRepoId: urlr-python
templateDir: openapi-generator/templates/python